version: "3"
services:
  monitor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5050
  prometheus:
    image: prom/prometheus:v2.22.1
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
    links:
      - monitor

  grafana:
    image: grafana/grafana
    ports:
      - 3040:3000
    links:
      - prometheus
    volumes:
      - monitor_grafana:/var/lib/grafana
volumes:
  monitor_grafana: